// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmlsgblvpfylsfbxyylq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtbHNnYmx2cGZ5bHNmYnh5eWxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1NTM5NDQsImV4cCI6MjA4ODEyOTk0NH0.5l8rcpr6ZZPlQVzsE8FgTFWFS6bFYpOKRnsP_-HA4R8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});